config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'tasks' => 'tasks#index'
  get 'up' => 'rails/health#show', as: :rails_health_check
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new'
  get 'task/:id', to: 'tasks#show', as: 'task'
  get 'task/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'task/:id', to: 'tasks#update', as: 'update_task'
  delete 'task/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy

    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path status: :see_other
  end


  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.label :completed %>
  <%= form.check_box :completed %>
  <%= form.submit %>

<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task)%><%= link_to "Delete",
  destroy_task_path(task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%></li>
<% end %>

<%= link_to "Add a new task", tasks_new_path%>

app/views/tasks/new.html.erb
<%= form_with model: @task do |task|%>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <%= task.label :details %>
  <%= task.text_field :details %>
  <%= task.submit %>
<% end %>

<%= link_to "Back to list", tasks_path%>

app/views/tasks/show.html.erb
<h1><%=@task.title%></h1>
<p><%=@task.details%></p>
<p></p>
<%= "this task is completed" if @task.completed == true %>
<%= link_to "Back to list", tasks_path%>
<%= link_to "Edit this task", edit_task_path%>